import type { UserRole } from '../db/schema.js'

/** Stable permission keys. Catalog is code-owned; DB stores grants only. */
export const PERMISSION_CATALOG = [
  { key: 'users.view', category: 'people', description: 'View staff roster' },
  { key: 'users.manage', category: 'people', description: 'Create and update staff' },
  { key: 'sessions.revoke', category: 'people', description: 'Revoke own or others sessions' },
  { key: 'roles.manage', category: 'people', description: 'Edit farm roles and grants' },
  { key: 'security.admin', category: 'people', description: 'Security dashboard and TOTP admin' },
  { key: 'breakglass.cleanup', category: 'people', description: 'Break-glass admin deactivate' },
  { key: 'vault.view', category: 'integrations', description: 'View all portal vault entries (leave off to only see logins shared with you)' },
  { key: 'vault.manage', category: 'integrations', description: 'Create/update/delete vault entries' },
  { key: 'vault.reveal', category: 'integrations', description: 'Reveal vault passwords' },
  { key: 'tasks.work_own', category: 'tasks', description: 'Work assigned tasks' },
  { key: 'tasks.assign', category: 'tasks', description: 'Assign tasks' },
  { key: 'tasks.approve', category: 'tasks', description: 'Approve completed tasks' },
  { key: 'attendance.roster', category: 'tasks', description: 'View attendance roster' },
  { key: 'inventory.read', category: 'operations', description: 'View inventory' },
  { key: 'inventory.write', category: 'operations', description: 'Edit inventory items and movements' },
  { key: 'inventory.count', category: 'operations', description: 'Submit inventory counts' },
  { key: 'assets.count', category: 'operations', description: 'Submit equipment and asset counts' },
  { key: 'maintenance.read', category: 'operations', description: 'View equipment maintenance plans and history' },
  { key: 'maintenance.write', category: 'operations', description: 'Schedule and manage maintenance work' },
  { key: 'maintenance.complete', category: 'operations', description: 'Start and complete assigned maintenance work' },
  { key: 'scan.use', category: 'operations', description: 'Scan farm QR codes and barcodes' },
  { key: 'contractors.read', category: 'people', description: 'View contractors and active engagements' },
  { key: 'contractors.write', category: 'people', description: 'Manage contractors, engagements, and payments' },
  { key: 'anomalies.read', category: 'reports', description: 'View review-only anomaly observations and their evidence' },
  { key: 'anomalies.review', category: 'reports', description: 'Run anomaly checks and record review outcomes' },
  { key: 'census.create', category: 'operations', description: 'Submit crop census observations' },
  { key: 'livestock.log', category: 'operations', description: 'Record livestock feeding, vaccination, and mortality logs' },
  { key: 'field_reports.create', category: 'operations', description: 'Submit field observations and incident reports' },
  { key: 'knowledge.read', category: 'operations', description: 'Read approved operating guidelines' },
  { key: 'knowledge.write', category: 'operations', description: 'Draft and update operating guidelines' },
  { key: 'knowledge.approve', category: 'operations', description: 'Approve guidelines for staff and Farm AI' },
  { key: 'zones.manage', category: 'operations', description: 'Manage zones and plots' },
  { key: 'crops.manage', category: 'operations', description: 'Manage crops' },
  { key: 'livestock.manage', category: 'operations', description: 'Manage livestock' },
  { key: 'orders.read', category: 'orders', description: 'View orders' },
  { key: 'orders.manage', category: 'orders', description: 'Create and update orders' },
  { key: 'orders.pii', category: 'orders', description: 'View customer PII on orders' },
  { key: 'products.manage', category: 'orders', description: 'Manage product catalogue' },
  { key: 'products.delete', category: 'orders', description: 'Delete products' },
  { key: 'whatsapp.configure', category: 'comms', description: 'Configure WhatsApp integration' },
  { key: 'purchase_orders.approve', category: 'operations', description: 'Approve purchase orders' },
  { key: 'finance.read', category: 'finance', description: 'View finance' },
  { key: 'finance.write', category: 'finance', description: 'Create/update expenses' },
  { key: 'finance.delete', category: 'finance', description: 'Delete expenses' },
  { key: 'reports.read', category: 'reports', description: 'View reports' },
  { key: 'audit.export', category: 'reports', description: 'Export audit data' },
  { key: 'traceability.export', category: 'reports', description: 'Export traceability' },
  { key: 'whatsapp.send', category: 'comms', description: 'Send WhatsApp messages' },
  { key: 'telegram.send', category: 'comms', description: 'Use the Telegram butler and link a Telegram account' },
  { key: 'leads.manage', category: 'comms', description: 'Manage marketing leads from the website' },
  { key: 'newsletter.manage', category: 'comms', description: 'Manage newsletter' },
  { key: 'ai.use', category: 'comms', description: 'Use the role-scoped Trovara Copilot' },
  { key: 'integrations.view', category: 'comms', description: 'View integration status' },
  { key: 'journal.manage', category: 'comms', description: 'Manage journal posts' },
  { key: 'brand.manage', category: 'comms', description: 'Manage brand kit assets and press packs' },
  { key: 'moments.manage', category: 'comms', description: 'Review public Moments gallery submissions' },
  { key: 'careers.manage', category: 'comms', description: 'Manage careers listings for the marketing site' },
  { key: 'privacy.admin', category: 'people', description: 'Privacy export and retention' },
  { key: 'farm.manage', category: 'people', description: 'Edit farm profile, go-live, and demo reset' },
] as const

export type PermissionKey = (typeof PERMISSION_CATALOG)[number]['key']

/** Cannot be granted to non-owner custom roles. */
export const NON_DELEGABLE_PERMISSIONS = new Set<PermissionKey>([
  'roles.manage',
  'security.admin',
  'breakglass.cleanup',
  'vault.manage',
  'vault.reveal',
  'privacy.admin',
  'farm.manage',
  'whatsapp.configure',
  'products.delete',
])

const ALL_KEYS = PERMISSION_CATALOG.map((p) => p.key) as PermissionKey[]

export const SYSTEM_ROLE_TEMPLATES: Record<UserRole, { name: string; permissions: PermissionKey[] }> = {
  owner: {
    name: 'Admin',
    permissions: [...ALL_KEYS],
  },
  supervisor: {
    name: 'Supervisor',
    permissions: [
      'users.view',
      'sessions.revoke',
      'tasks.work_own',
      'tasks.assign',
      'tasks.approve',
      'attendance.roster',
      'inventory.read',
      'inventory.write',
      'inventory.count',
      'assets.count',
      'maintenance.read',
      'maintenance.write',
      'maintenance.complete',
      'scan.use',
      'contractors.read',
      'contractors.write',
      'anomalies.read',
      'anomalies.review',
      'census.create',
      'livestock.log',
      'field_reports.create',
      'knowledge.read',
      'knowledge.write',
      'knowledge.approve',
      'zones.manage',
      'crops.manage',
      'livestock.manage',
      'orders.read',
      'orders.manage',
      'orders.pii',
      'products.manage',
      'reports.read',
      'anomalies.read',
      'whatsapp.send',
      'telegram.send',
      'ai.use',
      'integrations.view',
      'vault.view',
      'purchase_orders.approve',
      'moments.manage',
    ],
  },
  sales: {
    name: 'Sales',
    permissions: [
      'sessions.revoke',
      'orders.read',
      'orders.manage',
      'orders.pii',
      'products.manage',
      'finance.read',
      'finance.write',
      'reports.read',
      'audit.export',
      'leads.manage',
      'ai.use',
      'integrations.view',
      'vault.view',
    ],
  },
  field_worker: {
    name: 'Field worker',
    permissions: [
      'sessions.revoke',
      'tasks.work_own',
      'inventory.count',
      'assets.count',
      'maintenance.read',
      'maintenance.complete',
      'scan.use',
      'census.create',
      'livestock.log',
      'field_reports.create',
      'knowledge.read',
      'ai.use',
    ],
  },
}

export function isPermissionKey(value: string): value is PermissionKey {
  return PERMISSION_CATALOG.some((p) => p.key === value)
}

export function filterDelegablePermissions(keys: string[]): PermissionKey[] {
  return keys.filter((k): k is PermissionKey => isPermissionKey(k) && !NON_DELEGABLE_PERMISSIONS.has(k))
}
